### ISSUE TITLE
Class 'FasterPay\Gateway' not found when place order  

### ISSUE THREAD

**Issue by nareshphp1** [FasterPay/module-magento2#1]
I am getting 
Fatal error: Uncaught Error: Class 'FasterPay\Gateway' not found in /public_html/app/code/Fasterpay/Fasterpay/Model/Fasterpay.php:137 when I place order with Fasterpay payment method. It is working fine with another payment methods. 

https://prnt.sc/rqv27g

**Comment by prashantbd** [comment]
Hi @nareshphp1 

Please share more information about your problem, we would like to know what PHP version you're using some more debugging information you can provide.

Alternatively, you can email us at integration@fasterpay.com.

Best Regards. 
Prashant.

**Comment by nareshphp1** [comment]
Hi @prashantbd 
I am using PHP Version 7.3.16. There is a class i.e. " use \FasterPay\Gateway as FPGateway; " in Model/Fasterpay.php which is showing not found.

**Comment by prashantbd** [comment]
Hi @nareshphp1 

Can you confirm if you have done the following step? 

After cloning the repository don't forget to install Fasterpay PHP API library (required): git submodule init and then git submodule update

Best Regards,
Prashant.

**Comment by nareshphp1** [comment]
Hi @prashantbd 
I install extension by composer and it working fine now.
cd <your Magento install dir>
composer require fasterpay/module-magento2 --no-update
composer update

I would like to suggest you to update Installation document with same steps that I did.
Best Regards
Naresh.

**Comment by prashantbd** [comment]
Hi @nareshphp1 

Thank you for the feedback, we'll work on that and update the documentation. 

Best Regards. 
Prashant.
